import type {
  TodayWeekStatusSlides,
  TomorrowWeekStatusSlides,
  WeekendWeekStatusSlides,
  WeeklyWeekStatusSlides,
} from "@ts/props";
import sourceData from "@assets/icons/mainInfoSection/sourceDataIcon.svg";

export const getWeekStatusSlide = (
  {
    todayMaxTemperature,
    todayMinTemperature,
    todayWindGusts,
    todayMinMaxWindSpeed,
    todayWeatherEffect,
    todayWeatherInfo,
    todayWindCategory,
  }: TodayWeekStatusSlides,
  {
    tomorrowWeatherEffect,
    tomorrowMinTemperature,
    tomorrowMaxTemperature,
    tomorrowMinMaxWindSpeed,
    tomorrowWindGusts,
    tomorrowWeatherInfo,
    tomorrowWindCategory,
  }: TomorrowWeekStatusSlides,
  {
    weekMinTemperature,
    weekMaxTemperature,
    weekMinMaxWindSpeed,
    weekWindGusts,
    weekWeatherEffect,
    weekWeatherInfo,
    weekWindCategory,
  }: WeeklyWeekStatusSlides,
  {
    weekendMinTemperature,
    weekendMaxTemperature,
    weekendMinMaxWindSpeed,
    weekendWindGusts,
    weekendWeatherEffect,
    weekendWeatherInfo,
    weekendWindCategory,
  }: WeekendWeekStatusSlides,
) => {
  return [
    {
      link: "",
      img: todayWeatherEffect,
      title: "Сегодня",
      info: todayWeatherInfo,
      minTemp: todayMinTemperature,
      maxTemp: todayMaxTemperature,
      windCategory: todayWindCategory,
      minMaxWindSpeed: todayMinMaxWindSpeed,
      windGusts: todayWindGusts,
      id: "Сегодня",
    },
    {
      link: "",
      img: tomorrowWeatherEffect,
      title: "Завтра",
      info: tomorrowWeatherInfo,
      minTemp: tomorrowMinTemperature,
      maxTemp: tomorrowMaxTemperature,
      windCategory: tomorrowWindCategory,
      minMaxWindSpeed: tomorrowMinMaxWindSpeed,
      windGusts: tomorrowWindGusts,
      id: "Завтра",
    },
    {
      link: "",
      img: weekWeatherEffect,
      title: "На этой неделе",
      info: weekWeatherInfo,
      minTemp: weekMinTemperature,
      maxTemp: weekMaxTemperature,
      windCategory: weekWindCategory,
      minMaxWindSpeed: weekMinMaxWindSpeed,
      windGusts: weekWindGusts,
      id: "На этой неделе",
    },
    {
      link: "",
      img: weekendWeatherEffect,
      title: "В выходные",
      info: weekendWeatherInfo,
      minTemp: weekendMinTemperature,
      maxTemp: weekendMaxTemperature,
      windCategory: weekendWindCategory,
      minMaxWindSpeed: weekendMinMaxWindSpeed,
      windGusts: weekendWindGusts,
      id: "В выходные",
    },
    {
      linkRout: "/",
      img: sourceData,
      title: "Источник данных",
      info: "Источник данных",
      staticText:
        "Нажмите чтобы посмотреть показания с источников погодных данных",
      id: "Источник даннных",
    },
  ];
};
